### ISSUE TITLE
Add Types

### ISSUE THREAD

**Issue by Sleitnick** [AtollStudios/Knit#128]
Add types to Knit. All libraries and core code should use Luau types.

**Comment by Sleitnick** [comment]
Some were added in v0.0.19-alpha.

**Comment by HawDevelopment** [comment]
Could you consider using emmylua notations and luau? This would make it a lot easier for people using roblox lsp.

**Comment by Sparkypen7** [comment]
> Could you consider using emmylua notations and luau? This would make it a lot easier for people using roblox lsp.

Luau typed annotations will be implemented.
