### ISSUE TITLE
Janitor has terrible performance issues

### ISSUE THREAD

**Issue by SilentsReplacement** [AtollStudios/Knit#138]
I did a performance test with bloatbomber's plugin for Janitor and my refactored [Maid](https://github.com/SilentsReplacement/Modules/blob/main/Maid.lua). The benchmark is simple, it sees the performance of adding and cleaning up tasks. The performance difference is the difference of a day and night:

![image](https://user-images.githubusercontent.com/71311544/129037634-28aab3dc-9661-4113-aa7e-45297d2200db.png)

Benchmark code: 

```lua
--[[

|WARNING| THESE TESTS RUN IN YOUR REAL ENVIRONMENT. |WARNING|

If your tests alter a DataStore, it will actually alter your DataStore.

This is useful in allowing your tests to move Parts around in the workspace or something,
but with great power comes great responsibility. Don't mess up your stuff!

---------------------------------------------------------------------

Documentation and Change Log:
https://devforum.roblox.com/t/benchmarker-plugin-compare-function-speeds-with-graphs-percentiles-and-more/829912/1

--------------------------------------------------------------------]]

local Maid = require(script.Maid)
local Janitor = require(script.Janitor)

local janitor = Janitor.new()
local maid = Maid.new()

return {

	ParameterGenerator = function()
		-- This function is called before running your function (outside the timer)
		-- and the return(s) are passed into your function arguments (after the Profiler). This sample
		-- will pass the function a random number, but you can make it pass
		-- arrays, Vector3s, or anything else you want to test your function on.
		return math.random(1000)/10
	end;

	Functions = {
		["Better Maid"] = function(Profiler, RandomNumber) -- You can change "Sample A" to a descriptive name for your function	
			
			maid:AddTask({
				Bo = function()

				end,

			}, "Bo")

			maid:AddTask({
				Destroy = function()

				end,
			}, "Bo")


			maid:Cleanup()
		end;

		["Janitor"] = function(Profiler, RandomNumber)
			
			
			janitor:Add({
				Bo = function()

				end,

			}, "Bo")

			janitor:Add({
				Destroy = function()

				end,
			}, "Bo")

			
			janitor:Cleanup()
		end;

		-- You can add as many functions as you like!
	};

}
```

**Comment by howmanysmall** [comment]
Performance isn't the main concern. This isn't something you should be worried about.

**Comment by howmanysmall** [comment]
I finally got around to this, but your benchmark is also completely wrong. The reason Janitor was slower was because it was warning you that you made a mistake.

![image](https://user-images.githubusercontent.com/26746527/129234982-f3e6a2bd-7cf1-457a-aba1-8dfca38c5776.png)

When you fix the benchmark, Janitor blows it completely out of the water.

![image](https://user-images.githubusercontent.com/26746527/129234929-41ea408d-e63b-4346-99c3-b2661bf15f34.png)

```lua
local Maid = require(script.Maid)
local Janitor = require(script.Janitor)

local RUN = 100

return {
	ParameterGenerator = function()
	end;

	Functions = {
		["Better Maid"] = function(Profiler)
			for _ = 1, RUN do
				local maid = Maid.new()
				maid:AddTask({
					Bo = function()
					end,
				}, "Bo")

				maid:AddTask({
					Destroy = function()
					end,
				}, "Destroy")

				maid:Cleanup()
			end
		end;

		["Janitor"] = function(Profiler, RandomNumber)
			for _ = 1, RUN do
				local janitor = Janitor.new()
				janitor:Add({
					Bo = function()
					end,
				}, "Bo")

				janitor:Add({
					Destroy = function()
					end,
				}, "Destroy")

				janitor:Cleanup()
			end
		end;
	};
}
```

It's not even a contest at this point.

**Comment by SilentsReplacement** [comment]
> I finally got around to this, but your benchmark is also completely wrong. The reason Janitor was slower was because it was warning you that you made a mistake.
> 
> ![image](https://user-images.githubusercontent.com/26746527/129234982-f3e6a2bd-7cf1-457a-aba1-8dfca38c5776.png)
> 
> When you fix the benchmark, Janitor blows it completely out of the water.
> 
> ![image](https://user-images.githubusercontent.com/26746527/129234929-41ea408d-e63b-4346-99c3-b2661bf15f34.png)
> 
> ```lua
> local Maid = require(script.Maid)
> local Janitor = require(script.Janitor)
> 
> local RUN = 100
> 
> return {
> 	ParameterGenerator = function()
> 	end;
> 
> 	Functions = {
> 		["Better Maid"] = function(Profiler)
> 			for _ = 1, RUN do
> 				local maid = Maid.new()
> 				maid:AddTask({
> 					Bo = function()
> 					end,
> 				}, "Bo")
> 
> 				maid:AddTask({
> 					Destroy = function()
> 					end,
> 				}, "Destroy")
> 
> 				maid:Cleanup()
> 			end
> 		end;
> 
> 		["Janitor"] = function(Profiler, RandomNumber)
> 			for _ = 1, RUN do
> 				local janitor = Janitor.new()
> 				janitor:Add({
> 					Bo = function()
> 					end,
> 				}, "Bo")
> 
> 				janitor:Add({
> 					Destroy = function()
> 					end,
> 				}, "Destroy")
> 
> 				janitor:Cleanup()
> 			end
> 		end;
> 	};
> }
> ```
> 
> It's not even a contest at this point.

Yes, I think you should realize this is why I closed the issue.

**Comment by SilentsReplacement** [comment]
PS: There is no reason to reply to this issue when it is literally closed.

**Comment by howmanysmall** [comment]
There was one, it was educating on the matter.
