### ISSUE TITLE
Components break with 2 or more RequiredComponents

### ISSUE THREAD

**Issue by CaptinLetus** [AtollStudios/Knit#139]
After this commit, components break when they have 2 or more required components.  https://github.com/AtollStudios/Knit/pull/124/commits/5f65f28b5a3d0e66824251a56fa6f06c065ce1bd

Reverting this commit fixes the issue.

The error: 
![image](https://user-images.githubusercontent.com/53979157/129448636-9dd9bace-0ca9-43a8-a7a5-59fb1c94760e.png)

**Comment by Sleitnick** [comment]
Fixed in https://github.com/AtollStudios/Knit/pull/144
