### ISSUE TITLE
The RunService methods of a component don't stop when a component is destroyed

### ISSUE THREAD

**Issue by angrybino** [AtollStudios/Knit#151]
The `HeartbeatUpdate`, `SteppedUpdate` and `RenderSteppedUpdate`, methods of a component are still called every despite if the component is destroyed.

**Comment by Sleitnick** [comment]
Do you have any code to reproduce the issue?

**Comment by SilentsReplacement** [comment]
Any basic code of a knit component should do:


```
local HotAirBalloon = {}

HotAirBalloon.__index = HotAirBalloon
HotAirBalloon.Tag = "HotAirBalloon"

function HotAirBalloon.new()
	return setmetatable({
	}, HotAirBalloon)
end

function HotAirBalloon:Init()
         -- Remove the tag
	game:GetService("CollectionService"):RemoveTag(self.Instance, HotAirBalloon.Tag)
       
end

function HotAirBalloon:HeartbeatUpdate(deltaTime)
	print(deltaTime)
end

function HotAirBalloon:Destroy()
	
end
```

**Comment by howmanysmall** [comment]
i've had this problem in non-fusion related code

**Comment by SilentsReplacement** [comment]
I've released a pull request which fixes this issue. See: https://github.com/AtollStudios/Knit/pull/152 @Sleitnick.

**Comment by SilentsReplacement** [comment]
Reopening this until the problem is fixed.

**Comment by Sleitnick** [comment]
I could not replicate this issue. I copy & pasted your code, and it didn't have any issues.

The `self._objects` table never changes, thus there is no problem referencing it within the lifecycle methods as `local all = self._objects`.

Are you on the latest Knit version?

**Comment by angrybino** [comment]
Yes, I'm on the latest Knit version. However, I'll be closing this issue as I've created my own framework.
