### ISSUE TITLE
Unhandled Promise rejection

### ISSUE THREAD

**Issue by Ductayp** [AtollStudios/Knit#156]
when starting up bare new project with the latest version of Knit, I get a promise error, please see screenshot:
https://i.imgur.com/xmRS8cc.png

```
  12:43:40.307  Unhandled Promise rejection:

Unexpected response when fetching game name, no game info

CoreGui.RobloxGui.Modules.Common.GetGameNameAndDescriptionNew:24
CorePackages.Packages._Index.evaera_roblox-lua-promise.roblox-lua-promise:151 function runExecutor
CorePackages.Packages._Index.evaera_roblox-lua-promise.roblox-lua-promise:160
  -  Client - roblox-lua-promise:1294
  ```

**Comment by Ductayp** [comment]
I found a thread on the developer forums: https://devforum.roblox.com/t/mysterious-bug-output/1469886/8

I changed my game description and the error went away. Still, we should prevent that form happening

**Comment by howmanysmall** [comment]
This is likely a Roblox bug and not something that should be dealt with on Knit. If anything, this would be dealt with on the actual Promise library, but again, it's not something for users to handle.

**Comment by Sleitnick** [comment]
This is not an issue with promises, but whatever your `GetGameNameAndDescriptionNew` module is. Your code is throwing an error for some reason, and the Promise is simply bubbling up the unhandled error.

When errors are thrown within promises, you will get "Unhandled Promise rejection" messages if you're not adding Catch clauses to your promise chains.
